# Generated by Django 4.0.2 on 2022-02-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания задания')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на видео')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название видео')),
                ('min_view', models.IntegerField(verbose_name='Время минимального просмотра в с.')),
                ('max_view', models.IntegerField(verbose_name='Время максимального просмотра в с.')),
                ('thread_view', models.IntegerField(verbose_name='Количество потоков для просмотра')),
                ('count_view', models.IntegerField(verbose_name='Количество раз просмотрено')),
                ('avalible', models.BooleanField(verbose_name='Просматривать')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
                'ordering': ['-created'],
            },
        ),
    ]
