# Generated by Django 4.0.2 on 2022-03-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worked', models.BooleanField(default=False, null=True, verbose_name='Выполняется алгоритм')),
                ('worked_video', models.IntegerField(default=0, verbose_name='Видео в работе')),
            ],
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
        migrations.AlterField(
            model_name='video',
            name='avalible',
            field=models.BooleanField(default=True, verbose_name='Просматривать'),
        ),
        migrations.AlterField(
            model_name='video',
            name='count_view',
            field=models.IntegerField(default=0, verbose_name='Количество раз просмотрено'),
        ),
        migrations.AlterField(
            model_name='video',
            name='max_view',
            field=models.IntegerField(default=60, verbose_name='Время максимального просмотра в с.'),
        ),
        migrations.AlterField(
            model_name='video',
            name='min_view',
            field=models.IntegerField(default=30, verbose_name='Время минимального просмотра в с.'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thread_view',
            field=models.IntegerField(default=10, verbose_name='Количество потоков для просмотра'),
        ),
    ]
